### ISSUE TITLE
Serving multiple domains

### ISSUE THREAD

**Issue by priyadarshan** [Hukadan/nodebb-devel-port#1]
Hi,
Having installed Nodebb via pkg, thanks to `nodebb-devel-port`, I see that it is of course installed in `/usr/local/www/nodebb`.

Since each instance of nodebb rely on a given `config.json` (ie, each domain must have its own config.json) I was wondering how can one serve nodebb from more than one domain?

Of course one could make multiple installs, using jails, but it feels a little heavy.

Is there a lighter way to deal with that use-case?

**Comment by Hukadan** [comment]
I think using jail would be the way to go. In fact, my NodeBB forum runs in a jail. Plus, when you want to test some update, you can clone the jail and safely make some tests with an exact copy of your forum. iocage (for one) makes managing multiple jails a peace of cake. Put a nginx proxy to handle the different domains. That's how I would do it.

**Comment by priyadarshan** [comment]
Excellent, I shall do that. Thank you again for `nodebb-devel-port`!

**Comment by priyadarshan** [comment]
> Put a nginx proxy to handle the different domains.

Would you mind sharing the related nginx conf block for that?

**Comment by Hukadan** [comment]
You have good examples in the NodeBB documentations : https://docs.nodebb.org/en/latest/configuring/proxies/nginx.html

**Comment by priyadarshan** [comment]
Thank you.
